language: python
python:
  - "2.7"
  - "3.6"
branches:
  only:
    - develop
install:
  - python setup.py install
  - pip install tensorflow
script: pytest --cov-report term --cov=innvestigate
after_success:
    - codecov
